version: '2'
services:
    reeceaddressbook-app:
        image: reeceaddressbook
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://reeceaddressbook-mysql:3306/reeceaddressbook?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    reeceaddressbook-mysql:
        extends:
            file: mysql.yml
            service: reeceaddressbook-mysql
